#                  _            _
#  __   _____ _ __| |_ _____  _| |__   _____  __
#  \ \ / / _ \ '__| __/ _ \ \/ / '_ \ / _ \ \/ /
#   \ V /  __/ |  | ||  __/>  <| |_) | (_) >  <
#    \_/ \___|_|   \__\___/_/\_\_.__/ \___/_/\_\
#
#
#  Copyright (C) 2023-2024 @vertexbox <https://github.com/vertexbox>
#
#  This is a open-source software, licensed under the MIT License.
#  See /License for more information.

name: Get git revision count
description: "get the number of git revision associated to a specific ref"

inputs:
  ref:
    type: string
    description: "git ref"

runs:
  using: composite
  steps:
    - name: Get revision count
      id: rev_count
      env:
        REF: ${{ inputs.ref }}
      run: |
        echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
