#                  _            _
#  __   _____ _ __| |_ _____  _| |__   _____  __
#  \ \ / / _ \ '__| __/ _ \ \/ / '_ \ / _ \ \/ /
#   \ V /  __/ |  | ||  __/>  <| |_) | (_) >  <
#    \_/ \___|_|   \__\___/_/\_\_.__/ \___/_/\_\
#
#
#  Copyright (C) 2023-2024 @vertexbox <https://github.com/vertexbox>
#
#  This is a open-source software, licensed under the MIT License.
#  See /License for more information.

name: Run unit tests

on:
  workflow_dispatch:
  push:
    path:
      - common/**/*.yaml
      - container/**/*.yaml
      - git/**/*.yaml
      - github/**/*.yaml
      - .github/workflows/run-unit-tests.yaml

defaults:
  run:
    working-directory: tests # The working directory path

jobs:
  # common
  common-log-github-context-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: vertexbox/github-seed-actions/common/log-github-context/test@master

  # git
  git-git-revision-count-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: vertexbox/github-seed-actions/git/git-revision-count/test@master

  git-git-commit-metadata-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: vertexbox/github-seed-actions/git/git-commit-metadata/test@master

  # github
  rss-to-issue-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: vertexbox/github-seed-actions/github/rss-to-issue/test@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
